version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

executors:
  nais-deployer:
    environment:
      TEAM: teamffamilie
    docker:
      - image: navikt/deployment-cli:latest

jobs:
  build_n_test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
         docker_layer_caching: true
      - run:
          name: Generate version number, github token and docker image tags
          command: |
            mkdir /tmp/workspace
            export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"
            echo "export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"" >> /tmp/workspace/properties.env
            echo "export DOCKER_TAG=\"$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> /tmp/workspace/properties.env
            cat /tmp/workspace/properties.env >> $BASH_ENV
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/node_modules
      - run:
          name: Bygger produksjon
          command: |
            cp ./.circleci/oauth2.js ./node_modules/oauth/lib/oauth2.js
            yarn build
      - run:
          name: Bygger Docker image
          command: |
            echo $DOCKER_TAG $VERSION
            docker build -t $DOCKER_TAG .
      - run:
          name: Docker push
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin 
            echo "Pushing with tag $DOCKER_TAG"
            docker push $DOCKER_TAG
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - properties.env

  github_app:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - run:
          name: Creating Github Apps Installation Token
          command: |
            git clone https://github.com/navikt/github-apps-support.git
            export PATH=`pwd`/github-apps-support/bin:$PATH
            echo $GITHUB_PRIVATE_KEY | base64 --decode > ./github.key.pem
            GITHUB_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./github.key.pem $GITHUB_APP_ID`)
      - persist_to_workspace:
          root: .
          paths:
            - ./github.key.pem

  deploy_test:
      executor: nais-deployer
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - checkout
        - run:
            name: Set up environment variables
            command: cat /tmp/workspace/properties.env >> $BASH_ENV
        - run:
            name: Create github deployment for stable test
            command: |
              deployment-cli deploy create \
              --cluster=dev-fss \
              --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --appid=${GITHUB_APP_ID} \
              --team=${TEAM} \
              --version=${VERSION} \
              --key=/tmp/workspace/github.key.pem \
              --resource=./naiserator_preprod.yaml

  deploy_prod:
      executor: nais-deployer
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - checkout
        - run:
            name: Set up environment variables
            command: cat /tmp/workspace/properties.env >> $BASH_ENV
        - run:
            name: Create github deployment for production
            command: |
              deployment-cli deploy create \
              --cluster=prod-fss \
              --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
              --appid=${GITHUB_APP_ID} \
              --team=${TEAM} \
              --version=${VERSION} \
              --key=/tmp/workspace/github.key.pem \
              --resource=./naiserator_preprod.yaml

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - build_n_test:
          context: NAIS deployment
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - github_app:
          context: familie-ci
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - deploy_test:
          context: familie-ci
          requires:
            - build_n_test
            - github_app
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - deploy_prod:
          context: familie-ci
          requires:
            - build_n_test
            - github_app
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+$/